
tasks:
  - name: initialize
    before: |
      echo "🤔 before"
    init: |
      echo "🚀 init"
      #npm install
      wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
      dapr init
      clear

ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 6379
    visibility: public
  - port: 9411
    visibility: public
  - port: 50005
    visibility: public

vscode:
  extensions:
    - pkief.material-icon-theme
    - aaron-bond.better-comments